#################################################
# Primer Commit main Turbo
# *Subir a Github
# * Index.py
# ejecutable.exe
# release: 26/10/2022
# developer: Lucas Leon
################################################

#VARIABLES
tamanio = 22.4, 44.8, 67.2

marca = "GARRET", "KKK", "MITSUBISHI", "T0YOTA", "BORG WARNER" , "Ihi" , "HOLSET"

zona = 1,2,3,4

#index
x = tamanio.index(44.8)

y = marca.index("GARRET")

z = zona.index(1)

tamanio = input("ingrese tamanio")
print("usted quiere" + tamanio)

marca = input("ingrese marca")
print ("usted quiere" + marca)

zona = input("ingrese zona")
print ("usted eligio" + zona)